- name: Installing nginx
  package:
   - name: nginx
     state: present

- name: Download and extract
  ansible.builtin.unarchive:
  src: https://github.com/stans-robot-project/frontend/archive/main.zip
  dest: /usr/share/nginx/html
  remote_src: yes
