- name : demo on facts
  hosts: all
  tasks:
   - name: printing URL
     ansible.builtin.debug:
       msg: OS Distro is {{ansible_distribution}}

   - name: printing URL
     ansible.builtin.debug:
       msg: Mac address is {{ansible_default_ipv4.macaddress}}
     